server:
  port: 0

spring:
  data:
    elasticsearch:
      cluster-name: elastic-cluster
      cluster-nodes: localhost:9300
      host: localhost
      port: 9300
      repositories:
        enabled: true
      properties:
        http:
          enabled: true

xpack:
  security:
    enabled: false

search:
  queryLimitInHours: 24


